receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  # Logs to console
  debug:
    verbosity: detailed

  # Metrics to Prometheus endpoint
  prometheus:
    endpoint: 0.0.0.0:9090
    namespace: otel

  # Traces to Jaeger
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  otlp/otelproxy:
    endpoint: api:8000
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger, otlp/otelproxy]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, otlp/otelproxy]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/otelproxy]
