{{- if .Values.db.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: {{ .Values.namespace }}
  labels:
    app: db
spec:
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.db.image }}
          ports:
            - containerPort: {{ .Values.db.service.port }}
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.env.POSTGRES_PASSWORD | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.db.env.POSTGRES_USER | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.db.env.POSTGRES_DB | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: db
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.port }}
{{- end }}




