name: Default Snapshot Images Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release (e.g., "0.1.2")
        required: true
        default: '0.0.0-dev'

env:
  VERSION: ${{ inputs.version }}
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

jobs:
  docker_build:
    runs-on: release-runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: daytonaio
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push the default snapshot image
        uses: docker/build-push-action@v5
        with:
          context: ./images/sandbox
          file: ./images/sandbox/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            daytonaio/sandbox:${{ env.VERSION }}
            daytonaio/sandbox:latest

      - name: Build and push the default snapshot slim image
        uses: docker/build-push-action@v5
        with:
          context: ./images/sandbox-slim
          file: ./images/sandbox-slim/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            daytonaio/sandbox:${{ env.VERSION }}-slim
            daytonaio/sandbox:latest-slim
