name: daytona project-config add
synopsis: Add a project config
usage: daytona project-config add [flags]
options:
    - name: branch
      usage: Specify the Git branch to use in the project
    - name: builder
      usage: Specify the builder (currently auto/devcontainer/none)
    - name: custom-image
      usage: |
        Create the project with the custom image passed as the flag value; Requires setting --custom-image-user flag as well
    - name: custom-image-user
      usage: |
        Create the project with the custom image user passed as the flag value; Requires setting --custom-image flag as well
    - name: devcontainer-path
      usage: |
        Automatically assign the devcontainer builder with the path passed as the flag value
    - name: env
      default_value: '[]'
      usage: |
        Specify environment variables (e.g. --env 'KEY1=VALUE1,KEY2=VALUE2,...')
    - name: manual
      default_value: "false"
      usage: Manually enter the Git repository
    - name: name
      usage: Specify the project config name
inherited_options:
    - name: help
      default_value: "false"
      usage: help for daytona
see_also:
    - daytona project-config - Manage project configs
