name: daytona target-config
synopsis: Manage targets configs
inherited_options:
    - name: help
      default_value: "false"
      usage: help for daytona
see_also:
    - daytona - Daytona is a Dev Environment Manager
    - daytona target-config list - List target configs
    - daytona target-config remove - Remove target config
    - daytona target-config set - Set target config
    - daytona target-config set-default - Set default target config
