name: daytona project-config
synopsis: Manage project configs
inherited_options:
    - name: help
      default_value: "false"
      usage: help for daytona
    - name: output
      shorthand: o
      usage: Output format. Must be one of (yaml, json)
see_also:
    - daytona - Daytona is a Dev Environment Manager
    - daytona project-config add - Add a project config
    - daytona project-config delete - Delete a project config
    - daytona project-config info - Show project config info
    - daytona project-config list - Lists project configs
    - daytona project-config update - Update a project config
