name: daytona target-config set
synopsis: Set target config
usage: daytona target-config set [flags]
inherited_options:
    - name: help
      default_value: "false"
      usage: help for daytona
see_also:
    - daytona target-config - Manage targets configs
